# Generated by Django 6.0.1 on 2026-01-28 01:02

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('total_calories_consumed', models.IntegerField(default=0)),
                ('total_budget_spent', models.FloatField(default=0.0)),
                ('water_intake_cups', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='api.userprofile')),
            ],
            options={
                'unique_together': {('user', 'date')},
            },
        ),
    ]
