# Generated by Django 6.0.1 on 2026-01-28 01:17

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_dailysummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercustommeal',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='MealLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('quantity', models.FloatField(default=1.0)),
                ('prep_style', models.CharField(choices=[('LIGHT', 'Light'), ('STANDARD', 'Standard'), ('HEAVY', 'Heavy')], default='STANDARD', max_length=10)),
                ('final_calories', models.IntegerField(editable=False)),
                ('final_price', models.FloatField(editable=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('custom_meal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meal_logs', to='api.usercustommeal')),
                ('meal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meal_logs', to='api.basemeal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_logs', to='api.userprofile')),
            ],
        ),
        migrations.DeleteModel(
            name='DailyLog',
        ),
    ]
