# Generated by Django 6.0.1 on 2026-01-28 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_ingredient_recipe_recipeitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='body_fat_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='diet_mode',
            field=models.CharField(choices=[('BALANCED', 'Balanced'), ('KETO', 'Keto'), ('VEGAN', 'Vegan'), ('HIGH_PROTEIN', 'High Protein')], default='BALANCED', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
    ]
