# Generated by Django 6.0.1 on 2026-01-30 00:23

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_userprofile_body_fat_percentage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EgyptianMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_id', models.CharField(max_length=50, unique=True)),
                ('name_en', models.CharField(max_length=100)),
                ('name_ar', models.CharField(blank=True, max_length=100, null=True)),
                ('default_serving_weight_g', models.IntegerField(default=300)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Egyptian Meal',
                'verbose_name_plural': 'Egyptian Meals',
            },
        ),
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='ingredient',
            name='calories_per_100g',
            field=models.FloatField(default=0, help_text='Calories per 100g'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='carbs_per_100g',
            field=models.FloatField(default=0, help_text='Carbohydrates (g) per 100g'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='fat_per_100g',
            field=models.FloatField(default=0, help_text='Fat (g) per 100g'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='fiber_per_100g',
            field=models.FloatField(default=0, help_text='Fiber (g) per 100g'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='protein_per_100g',
            field=models.FloatField(default=0, help_text='Protein (g) per 100g'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='usda_id',
            field=models.CharField(blank=True, help_text='USDA FoodData Central ID', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='calories_per_unit',
            field=models.FloatField(default=0, help_text='Calories for 1g, 1ml or 1 piece'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='price_per_unit',
            field=models.FloatField(default=0, help_text='Price for 1g, 1ml or 1 piece'),
        ),
        migrations.CreateModel(
            name='DailyPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=50)),
                ('item_name', models.CharField(max_length=100)),
                ('price_egp', models.FloatField()),
                ('unit', models.CharField(max_length=50)),
                ('store_name', models.CharField(default='carrefour_egypt', max_length=100)),
                ('date', models.DateField(default=datetime.date.today)),
                ('confidence', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('mock', 'Mock Data')], default='medium', max_length=10)),
                ('scraped_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-date', 'item_id'],
                'unique_together': {('item_id', 'store_name', 'date')},
            },
        ),
        migrations.CreateModel(
            name='MealRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.FloatField(help_text='Percentage by weight (0-100)')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_recipes', to='api.ingredient')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_items', to='api.egyptianmeal')),
            ],
            options={
                'ordering': ['-percentage'],
                'unique_together': {('meal', 'ingredient')},
            },
        ),
    ]
