# Generated by Django 6.0.1 on 2026-01-30 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_egyptianmeal_alter_ingredient_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meallog',
            name='egyptian_meal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meal_logs', to='api.egyptianmeal'),
        ),
    ]
