# Generated by Django 6.0.1 on 2026-02-01 03:41

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_weightlog'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dailyprice',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='basemeal',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='basemeal',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='dailyprice',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='dailyprice',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='dailysummary',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='dailysummary',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='marketprice',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='marketprice',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='meallog',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='mealrecipe',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='mealrecipe',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='recipe',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='recipeitem',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='recipeitem',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='usercustommeal',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usercustommeal',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='weightlog',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='basemeal',
            name='calories',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='basemeal',
            name='carbs_g',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=8),
        ),
        migrations.AlterField(
            model_name='basemeal',
            name='fats_g',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=8),
        ),
        migrations.AlterField(
            model_name='basemeal',
            name='meal_type',
            field=models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Snack', 'Snack')], default='Snack', max_length=20),
        ),
        migrations.AlterField(
            model_name='basemeal',
            name='name',
            field=models.CharField(default='Unnamed Meal', max_length=100),
        ),
        migrations.AlterField(
            model_name='basemeal',
            name='protein_g',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=8),
        ),
        migrations.AlterField(
            model_name='dailyprice',
            name='item_id',
            field=models.CharField(default='generic_item', max_length=100),
        ),
        migrations.AlterField(
            model_name='dailyprice',
            name='price_egp',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='dailysummary',
            name='total_budget_spent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='egyptianmeal',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='egyptianmeal',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='calories_per_100g',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='calories_per_unit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='carbs_per_100g',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=8),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='fat_per_100g',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=8),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='fiber_per_100g',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=8),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='price_per_unit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='protein_per_100g',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=8),
        ),
        migrations.AlterField(
            model_name='marketprice',
            name='price_egp',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='meallog',
            name='custom_meal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_meal_logs', to='api.usercustommeal'),
        ),
        migrations.AlterField(
            model_name='meallog',
            name='egyptian_meal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='egyptian_meal_logs', to='api.egyptianmeal'),
        ),
        migrations.AlterField(
            model_name='meallog',
            name='final_calories',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='meallog',
            name='final_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='meallog',
            name='meal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='standard_meal_logs', to='api.basemeal'),
        ),
        migrations.AlterField(
            model_name='meallog',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.0'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='mealrecipe',
            name='percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('100.0'), help_text='Percentage by weight (0-100)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='recipeitem',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='usercustommeal',
            name='calories',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usercustommeal',
            name='carbs_g',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=8),
        ),
        migrations.AlterField(
            model_name='usercustommeal',
            name='fats_g',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=8),
        ),
        migrations.AlterField(
            model_name='usercustommeal',
            name='name',
            field=models.CharField(default='Unnamed Meal', max_length=100),
        ),
        migrations.AlterField(
            model_name='usercustommeal',
            name='protein_g',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=8),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='activity_level',
            field=models.CharField(choices=[('Sedentary', 'Sedentary'), ('Light', 'Light'), ('Lightly Active', 'Lightly Active'), ('Moderate', 'Moderate'), ('Moderately Active', 'Moderately Active'), ('Active', 'Active'), ('Very Active', 'Very Active'), ('Extremely Active', 'Extremely Active')], default='Sedentary', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='body_fat_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='daily_budget_limit',
            field=models.DecimalField(decimal_places=2, default=Decimal('50.0'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='goal_weight',
            field=models.DecimalField(decimal_places=2, default=Decimal('70.0'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='height',
            field=models.DecimalField(decimal_places=2, default=Decimal('170.0'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=Decimal('70.0'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='weightlog',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='weightlog',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=5),
        ),
    ]
