# Generated by Django 6.0.1 on 2026-02-03 04:31

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_dailyprice_unique_together_basemeal_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealrecipe',
            name='usage_ratio',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.0'), help_text='Pantry Protocol: 0.1 for spice/oil splashes', max_digits=4),
        ),
    ]
