# Generated by Django 6.0.1 on 2026-02-03 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_mealrecipe_usage_ratio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealrecipe',
            name='usage_ratio',
        ),
        migrations.AddField(
            model_name='marketprice',
            name='is_price_verified',
            field=models.BooleanField(default=False),
        ),
    ]
