# Generated by Django 6.0.1 on 2026-02-03 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_mealrecipe_usage_ratio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='basemeal',
            name='is_healthy',
            field=models.BooleanField(default=False),
        ),
    ]
