# Generated by Django 6.0.1 on 2026-02-06 00:26

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_daystatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='basemeal',
            name='fiber_g',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), help_text='Dietary fiber in grams', max_digits=8),
        ),
        migrations.AddField(
            model_name='basemeal',
            name='serving_weight',
            field=models.IntegerField(default=100, help_text='Serving size in grams'),
        ),
        migrations.AddField(
            model_name='usercustommeal',
            name='fiber_g',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), help_text='Dietary fiber in grams', max_digits=8),
        ),
        migrations.AddField(
            model_name='usercustommeal',
            name='serving_weight',
            field=models.IntegerField(default=100, help_text='Serving size in grams'),
        ),
    ]
