# Generated by Django 6.0.1 on 2026-02-06 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_basemeal_fiber_g_basemeal_serving_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='basemeal',
            name='name_ar',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='name_ar',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='basemeal',
            name='meal_type',
            field=models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Snack', 'Snack'), ('Salads', 'Salads')], default='Snack', max_length=20),
        ),
    ]
