# Generated by Django 6.0.1 on 2026-02-06 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_basemeal_name_ar_ingredient_name_ar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='name_ar',
            field=models.CharField(blank=True, help_text='Arabic recipe name', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usercustommeal',
            name='name_ar',
            field=models.CharField(blank=True, help_text='Arabic meal name', max_length=100, null=True),
        ),
    ]
