# Generated by Django 6.0.1 on 2026-02-06 07:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_recipe_name_ar_usercustommeal_name_ar'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysummary',
            name='hydration_goal_met',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='best_hydration_streak',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='current_hydration_streak',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='current_weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Current weight for diet planning', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hydration_level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='total_glasses_lifetime',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='HydrationAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('achievement_id', models.CharField(choices=[('FIRST_DROP', 'First Drop - Logged first glass'), ('HOT_STREAK', 'Hot Streak - 7 days hitting goal'), ('LIGHTNING', 'Lightning - 3 consecutive perfect days'), ('HYDRO_HERO', 'Hydro Hero - 30-day streak'), ('OCEAN_MASTER', 'Ocean Master - 100 total glasses'), ('LEVEL_5', 'Level 5 Unlocked'), ('LEVEL_10', 'Level 10 Unlocked')], max_length=50)),
                ('unlocked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('seen', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hydration_achievements', to='api.userprofile')),
            ],
            options={
                'ordering': ['-unlocked_at'],
                'unique_together': {('user', 'achievement_id')},
            },
        ),
    ]
