# Generated by Django 6.0.1 on 2026-02-08 00:34

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_dailysummary_hydration_goal_met_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basemeal',
            name='name',
            field=models.CharField(db_index=True, default='Unnamed Meal', max_length=100),
        ),
        migrations.AlterField(
            model_name='basemeal',
            name='name_ar',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dailysummary',
            name='date',
            field=models.DateField(db_index=True, default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='daystatus',
            name='date',
            field=models.DateField(db_index=True, default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='egyptianmeal',
            name='name_ar',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='egyptianmeal',
            name='name_en',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='marketprice',
            name='is_price_verified',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='meallog',
            name='date',
            field=models.DateField(db_index=True, default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='usercustommeal',
            name='name',
            field=models.CharField(db_index=True, default='Unnamed Meal', max_length=100),
        ),
        migrations.AlterField(
            model_name='usercustommeal',
            name='name_ar',
            field=models.CharField(blank=True, db_index=True, help_text='Arabic meal name', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='weightlog',
            name='date',
            field=models.DateField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
