# Generated by Django 6.0.1 on 2026-02-08 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_basemeal_name_alter_basemeal_name_ar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_plan_variant',
            field=models.IntegerField(default=0, help_text='Tracks the last used diet plan strategy (0-4) for rotation.'),
        ),
    ]
