# Generated by Django 6.0.1 on 2026-02-09 23:04

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_userprofile_last_plan_variant'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=100)),
                ('name_ar', models.CharField(max_length=100)),
                ('governorate', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('metro', 'Metropolitan'), ('major_city', 'Major City'), ('regional', 'Regional City'), ('provincial', 'Provincial City'), ('rural', 'Rural Area')], max_length=20)),
                ('price_multiplier', models.FloatField(default=1.0)),
            ],
            options={
                'verbose_name_plural': 'Cities',
                'ordering': ['name_en'],
            },
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='price_per_unit',
        ),
        migrations.AddField(
            model_name='basemeal',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), help_text='Cairo/Giza reference price in EGP', max_digits=10),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), help_text='Cairo/Giza reference price in EGP', max_digits=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='city',
            field=models.CharField(blank=True, help_text="User's city", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='location_category',
            field=models.CharField(choices=[('metro', 'Metropolitan (Cairo/Giza)'), ('major_city', 'Major City'), ('regional', 'Regional City'), ('provincial', 'Provincial City'), ('rural', 'Rural Area')], default='metro', help_text="Price category for user's location", max_length=20),
        ),
    ]
