# Generated by Django 6.0.1 on 2026-02-09 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_city_remove_ingredient_price_per_unit_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='City',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='city',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='location_category',
            field=models.CharField(choices=[('metro', 'Metropolitan (Cairo/Giza)'), ('major_city', 'Major City'), ('regional', 'Regional City'), ('provincial', 'Provincial City'), ('rural', 'Rural Area')], default='metro', help_text="Price category for user's location (Auto-assigned)", max_length=20),
        ),
    ]
