# Generated by Django 6.0.1 on 2026-02-09 23:20

from django.db import migrations


from api.utils.location_helpers import get_city_category

def populate_location_data(apps, schema_editor):
    UserProfile = apps.get_model('api', 'UserProfile')
    for profile in UserProfile.objects.all():
        if profile.current_location:
            profile.location_category = get_city_category(profile.current_location)
            profile.save()

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_delete_city_remove_userprofile_city_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_location_data),
    ]
