# Generated by Django 6.0.1 on 2026-02-10 01:54

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_populate_location_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercustommeal',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), help_text='Reference price in EGP', max_digits=10),
        ),
        migrations.AlterField(
            model_name='basemeal',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), help_text='Reference price in EGP', max_digits=10),
        ),
    ]
